
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: clinic_visualization_development
  username: postgres
  password: postgres
  host: localhost

  
test:
  <<: *default
  database: clinic_visualization_test
  username: postgres
  password: postgres
  host: localhost


production:
  <<: *default
  database: clinic_visualization_production
  username: clinic_visualization
  password: <%= ENV['CLINIC_VISUALIZATION_DATABASE_PASSWORD'] %>
