# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f077ce0797ab75c28e473e726af10694f1c0318689a74d0c1aef1a353598cd1ce225471a925133545cb6507b43937d63ff4116cdf938d2a1732325efafe7977

test:
  secret_key_base: 68152d594914c9018c9da5f95b84db24c5d2a9251da3f5ab97fdf8802f572e016e91b88486254c411e050ae07e0659bf263d2eb2d7607aea352cecacb363873c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
